import { Inter } from "next/font/google";
import "./globals.css";
import { Lalezar } from "next/font/google";
import { Roboto } from "next/font/google";


export const lalezar = Lalezar({ subsets: ["arabic"],weight:["400"] })
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"],weight:["100","300","400","500","700","900"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const lango = params.locale === "en" ? "ltr" : "rtl";
  return (
    <html lang={params.locale}>
      <body dir={lango}>
        {children}</body>
    </html>
  );
}
